aws/amazon-mwaa-docker-images

images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/System-Packages-BOM.txt
images/airflow/2.9.2/Dockerfiles/Dockerfile.base
images/airflow/2.9.2/bootstrap/03-root-secondpass/999-generate-bill-of-materials.sh
images/airflow/2.9.2/build.sh
quality-checks/pip_install_check.py

Created scripts to automate the building of Bill of Materials for Docker Image distribution. This PR achieves two things:
- It adds a bootstrap step to generate the Bill of Materials for both, OS and Python packages, and dump the content under the `/BillsOfMaterials` folder in the Docker Image for visibility.
- It syncs the generated files locally in the repo code so it gets automatically added in source control. This way, future updates to the used packages will automatically result in updating the files in the repo, thus making it easy to review as well.
---

Bill of Materials for Docker Image distribution

---

images/airflow/2.9.2/python/mwaa/entrypoint.py

*Issue #, if available:* #121
Fix issue #121. The issue is caused because we are trying to initialize the DB before installing the requirements. This causes this line in Airflow code base to fail because `sentry_sdk` isn't installed yet:
https://github.com/apache/airflow/blob/2.9.2/airflow/sentry.py#L58
To fix this issue, I moved the installation of PIP requirements before the DB initialization.
This is unrelated to this issue, but when creating a process to install the requirements, there is no need to pass the environment variables we craft for Airflow processes, as what we simply just running a pip install command.
---

Fix issue: Sentry causes failures in 2.9.2

---

images/airflow/2.9.2/docker-compose-hybrid.yaml
images/airflow/2.9.2/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/logging/config.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py

Adds the command 'hybrid' to the entrypoint script to allow creation of a container that runs both celery worker and scheduler sub-processes.
Introduces a new supported command 'hybrid' to run celery worker and scheduler sub-processes in the same docker container. Health-check conditions for the 'hybrid' container are limited to the 'worker ' sub-process because the Sidecar does not support multiple health-check simultaneous connections at this time. This 'hybrid' container uses the `CeleryExecutor`, but we plan to add a separate container command to support a `LocalExecutor` setup in the future.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Add hybrid scheduler/worker container

---

images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/System-Packages-BOM.txt
images/airflow/2.9.2/python/mwaa/database/migrate.py
images/airflow/2.9.2/python/mwaa/entrypoint.py

*Issue #, if available:* #124
Issue #124 happens because we are always calling `airflow db migrate` to make sure the database is migrated. The assumption was that the operation is a no-op if the DB is already initialized. However, this is not the case, and a reserialization of DAGs is happening every time this command is called. To avoid this, I am changing the code for executing migration to check if migration is needed.
I did multiple tests using the Docker Compose setup. More testing by Amazon MWAA developers before this PR is merged. Suggested testing:
1. Create an internal 2.9.2 environment and make sure it is functioning normally. Also check ECS logs to ensure there are no issues.
2. Create a pre-2.9.2 environment and do an in-place upgrade to 2.9.2 and make sure the process is …

Fix issue 123: Repeated reserialization of DAGs

---

images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/System-Packages-BOM.txt
images/airflow/2.9.2/explore-image.sh
images/airflow/2.9.2/python/mwaa/subprocess/__init__.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py

Performance testing MWAA airflow images revealed flaws with how logging is plumbed to CloudWatch. 
Currently, when airflow publishes log statements it is sent to an os pipe to be polled and read by the entrypoint process and then forwarded to cloudwatch. When this pipe is full, airflow must halt until logs are read before continuing execution. This means airflow execution is upper-bounded by how fast the entrypoint can read logs. 
The entrypoint has many other priorities in this critical loop (heartbeat healthcheck, db healthcheck, polling other subprocess logs, etc) and it has be measured that airflow scheduler is significantly throttled by this mechanism when log volume is large.
This PR aims to fix this by separating log polling into its own thread. This …

Refactor logging to be async

---

images/airflow/2.9.2/python/mwaa/subprocess/conditions.py

Fixing references to old subprocess status in AutoScalingCondition. The RUNNING_WITH_LOG_READ and RUNNING_WITH_NO_LOG_READ no longer exist and have been replaced by the RUNNING status.

Update references to subprocess status

---

images/airflow/2.9.2/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py

Discovered an issue where the worker healthchecks were not being performed in the hybrid container when the worker subprocess was run after the scheduler subprocess. Upon further investigation the root cause was determined to be the throttling conditions for the method `_check_process_conditions` which restricted the container to one call of the function per 60 seconds. This PR removes calls to `_check_process_conditions` in the subprocess `execution_loop_iter` loop if the subprocess does not have conditions. Also changes the throttle settings of `_check_process_conditions` to be instance level rather than global so that it is throttled per subprocess.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

Fix Hybrid Container Healthcheck Throttling

---

images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/System-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/System-Packages-BOM.txt
images/airflow/2.9.2/python/mwaa/entrypoint.py

*Issue #, if available:* fixes #126
Adding back passing of environment variables to pip package install. This allows the use of credentials via environment variables for private pypi repos. 

Pass environment variables to safe-pip-install

---

.github/workflows/quality-checks.yaml
.gitignore
README.md
create_venvs.py

52
*Description of changes:* 
Generate `requirements-dev.txt` file in the create_venvs script and replace psycopg2 with psycopg2-binary.
This means that pg_config will not be required for a development build.  psycopg2 should still be built from source for a production build as per the guidance of psycopg2-binary.

Generate dev version of requirements in create_venvs script

---

images/airflow/2.9.2/python/mwaa/celery/task_monitor.py
images/airflow/2.9.2/python/mwaa/subprocess/conditions.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py

Using throttling, each condition was being checked once per minute. But a condition may need to perform its check at a different pace like for example the TaskMonitor condition. This change applies throttling at individual condition instead of applying it generically at the subprocess level. The TaskMonitor condition will not be executed once per 10 seconds instead of one minute. This will allow for faster evaluation of worker idleness which would help in scaling down the worker fleet a lot more effectively.

Letting each condition control its frequency

---

.github/dependabot.yml

Closes #132 
Adds Airflow to the dependabot ignore list.

Add dependabot config with airflow ignored.

---

images/airflow/2.9.2/docker-compose-hybrid.yaml
images/airflow/2.9.2/docker-compose.yaml
images/airflow/2.9.2/python/mwaa/entrypoint.py

2.9.2 environments created after July 8(launch) and before Sept 6(fix deployed) have default_pool size 128 so we update this to 10000 (the value used for previous versions)

Update pool size if environment was created during problematic timeframe

---

images/airflow/2.10.1/python/mwaa/database/migrate.py
images/airflow/2.9.2/python/mwaa/database/migrate.py

N/A
`airflow initdb`, which was the defacto way to initialize the Airflow metadatabase, is now deprecated as of 2.7, and the command was split into: `airflow db migrate` and `airflow connections create-default-connections`. In our images, we are correctly using `airflow db migrate`, but did not port the default connection initialization. This leads to provider-related connections to not be created for new 2.9.2+ environments, which are required for many Operators; an AirflowNotFoundException will be thrown instead and fail the task. Providers' hooks fetch the connection [[base hook implementation]](https://github.com/apache/airflow/blob/4404e64247daf37b350bc7cd835d397256507ad1/airflow/hooks/base.py#L65), which does a lookup that will fail …

Load default Airflow connections on initialization

---

images/airflow/2.10.1/python/mwaa/database/migrate.py
images/airflow/2.9.2/python/mwaa/database/migrate.py

This reverts commit f71d082cac983385349f3e30b8a650d5f5c5d619.
N/A
Airflow startup is failing with:
```
mwaa-2101-scheduler  | [2024-11-27T19:46:26.107+0000] {cmd.py:85} INFO - File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 379, in set_extra
mwaa-2101-scheduler  | [2024-11-27T19:46:26.107+0000] {cmd.py:85} INFO - fernet = get_fernet()
mwaa-2101-scheduler  | [2024-11-27T19:46:26.108+0000] {cmd.py:85} INFO - ^^^^^^^^^^^^
mwaa-2101-scheduler  | [2024-11-27T19:46:26.108+0000] {cmd.py:85} INFO - File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/crypto.py", line 90, in get_fernet
mwaa-2101-scheduler  | [2024-11-27T19:46:26.108+0000] {cmd.py:85} INFO - raise …
```

Revert "Load default Airflow connections on initialization (#182)"

---

images/airflow/2.9.2/docker-compose.yaml
images/airflow/2.9.2/generate_fernet_key.py
images/airflow/2.9.2/run.sh
images/airflow/2.9.2/temporary-pip-install
quality-checks/lint_bash.sh
quality-checks/pip_install_check.py
quality-checks/run_all.py

*Issue #, if available:* #196
*Description of changes:* 
- Modified run.sh to generate, cache and pass valid fernet key to the docker-compose file.
- Added a script to be able to use pip install in run.sh to temporarily install dependencies needed before the bootstrap steps, like in this use-case.
- Updated pip_install_check.py and run_all.py quality_check files' shebang for better portability.
- Updated lint_bash check to exclude .venv's generated scripts.
*Description of testing:* 
- Built and ran image locally with the run.sh script.
- Used log statements to verify the fernet key was valid and being passed correctly.

Generate, cache and pass valid fernet keys for local deployment (#196)

---

images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/entrypoint.py

These changes fix an issue where an unsupported logger name was being used to try to publish startup script and requirements install logs for hybrid worker/scheduler containers. This issue resulted in missing requirements and startup script logs in CloudWatch. This fix adds logic to publish requirements and startup script logs via the worker logger in the case of hybrid container.s These changes were tested by deploying MWAA environments using Airflow 2.9.2, 2.10.1, and 2.10.3 to confirm the missing requirements and startup script logs are published to the worker CloudWatch log group.
---

Publish hybrid requirements and startup script logs to CloudWatch

---

images/airflow/2.10.1/docker-compose-hybrid.yaml
images/airflow/2.10.1/docker-compose-resetdb.yaml
images/airflow/2.10.1/docker-compose.yaml
images/airflow/2.10.3/docker-compose-hybrid.yaml
images/airflow/2.10.3/docker-compose-resetdb.yaml
images/airflow/2.10.3/docker-compose.yaml
images/airflow/2.9.2/docker-compose-hybrid.yaml
images/airflow/2.9.2/docker-compose-resetdb.yaml
images/airflow/2.9.2/docker-compose.yaml

Issue #, if available: [#176](https://github.com/aws/amazon-mwaa-docker-images/issues/176)
- Updated `Dockerfile.base.j2` file to include necessary url components to download `tini`.
- Updated `Dockerfile.derivatives.j2`, set the container entrypoint to use `tini` as init system and launches MWAA's Python entrypoint module.
- Added `tini` installation and permissions setup in `001-init.sh` script.
- Made the above changes to all airflow images.
Going forward to use docker's inbuilt init. Hence, enabling it in docker compose.
*Description of testing:*
- Built and ran image locally with the run.sh script.
- Checked if tini is running as PID#1 using `/proc/1/status`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Added tini as init process to all airflow images. (#176)

---

images/airflow/2.10.1/python/mwaa/config/setup_environment.py
images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.1/python/mwaa/execute_command.py
images/airflow/2.10.1/python/mwaa/logging/config.py
images/airflow/2.10.1/python/mwaa/subprocess/subprocess.py
images/airflow/2.10.1/python/mwaa/utils/user_requirements.py
images/airflow/2.10.3/python/mwaa/config/setup_environment.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/execute_command.py
images/airflow/2.10.3/python/mwaa/logging/config.py
images/airflow/2.10.3/python/mwaa/subprocess/subprocess.py
images/airflow/2.10.3/python/mwaa/utils/user_requirements.py
images/airflow/2.9.2/python/mwaa/config/setup_environment.py
images/airflow/2.9.2/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/execute_command.py
images/airflow/2.9.2/python/mwaa/logging/config.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py
images/airflow/2.9.2/python/mwaa/utils/user_requirements.py

When using airflow versions 2.9.2 and above customer are unable to see error logs when they set their loglevel to `WARNING` or above. The root cause is that in subprocess.py, the line `self.process_logger.info(line.decode("utf-8"))` overrides the log level coming from airflow stream to INFO in [subprocess.py](https://github.com/aws/amazon-mwaa-docker-images/blob/main/images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py#L217).
- Setting prcoess logger level to `DEBUG` to emit all logs and setting root logger to customer's log level to respect customer's log level.
- Refactoring `entrypoint.py` and breaking down its logic into different files so all files have single responsibility such as:
- `user_requirements.py`: Installing user …

Adding fix for incorrect bug and refactoring entrypoint.py to fix circular dependency issue

---

images/airflow/2.10.1/BillOfMaterials/2.10.1-dev/Python-Packages-BOM.txt
images/airflow/2.10.1/BillOfMaterials/2.10.1-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.10.1/BillOfMaterials/2.10.1-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.10.1/BillOfMaterials/2.10.1-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.10.1/BillOfMaterials/2.10.1-explorer/Python-Packages-BOM.txt
images/airflow/2.10.1/BillOfMaterials/2.10.1/Python-Packages-BOM.txt
images/airflow/2.10.1/python/mwaa/celery/task_monitor.py
images/airflow/2.10.3/BillOfMaterials/2.10.3-dev/Python-Packages-BOM.txt
images/airflow/2.10.3/BillOfMaterials/2.10.3-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.10.3/BillOfMaterials/2.10.3-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.10.3/BillOfMaterials/2.10.3-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.10.3/BillOfMaterials/2.10.3-explorer/Python-Packages-BOM.txt
images/airflow/2.10.3/BillOfMaterials/2.10.3/Python-Packages-BOM.txt
images/airflow/2.10.3/python/mwaa/celery/task_monitor.py
images/airflow/2.9.2/BillOfMaterials/2.9.2-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged-dev/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer-privileged/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2-explorer/Python-Packages-BOM.txt
images/airflow/2.9.2/BillOfMaterials/2.9.2/Python-Packages-BOM.txt
images/airflow/2.9.2/python/mwaa/celery/task_monitor.py

Graceful updates has introduced new logic and edge cases to the image code. This change adds new metrics to be emitted for those edge cases by the task monitor.

Graceful updates metrics

---

images/airflow/2.10.1/docker-compose.yaml
images/airflow/2.10.1/startup/startup.sh
images/airflow/2.10.3/docker-compose.yaml
images/airflow/2.10.3/startup/startup.sh
images/airflow/2.9.2/docker-compose.yaml
images/airflow/2.9.2/startup/startup.sh

The startup script didn't work for local docker image testing. So there was no way to test startup scripts.
- Added a startup script path environment variable in docker-compose file.
- Tested by running local docker image with a startup script.

Fix for start-up script not working in local docker image

---

images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/entrypoint.py
tests/images/airflow/2.10.1/python/mwaa/test_entrypoint_2_10_1.py
tests/images/airflow/2.10.3/python/mwaa/test_entrypoint_2_10_3.py
tests/images/airflow/2.9.2/python/mwaa/test_entrypoint_2_9_2.py

*Issue #, if available:N/A*
Currently, when `customer_env_vars.json` file fails to be created due to service-side issues, the error is only logged silently, which can cause issue later while debugging the main issue. This change makes the container fail explicitly by raising an exception instead of silently continuing execution.
*Testing:*
1. Verified container failure by simulating missing `customer_env_vars.json` file.
2. Confirmed appropriate error message is thrown.

Raise exception for missing customer_env_vars.json file.

---

images/airflow/2.10.1/python/mwaa/logging/cloudwatch_handlers.py
images/airflow/2.10.1/python/mwaa/logging/config.py
images/airflow/2.10.3/python/mwaa/logging/cloudwatch_handlers.py
images/airflow/2.10.3/python/mwaa/logging/config.py
images/airflow/2.9.2/python/mwaa/logging/cloudwatch_handlers.py
images/airflow/2.9.2/python/mwaa/logging/config.py

*Issue #, if available:N/A*
**Description of changes:**
Added log formatter for subprocess that only runs startup script and installs requirements file. This will help to avoid the risk of eliminating need of adding log level to the log message explicitly. We did not added log formatter to the core airflow subprocess because it already logs the data correctly and in required format.
**Testing**
Ran the container locally and checked if log level prefix is being added before the logs or not.
*Before log formatter*
*After log formatter*

Format subprocess logs for startup script and requirements subprocess.

---

.coveragerc
.gitignore
images/airflow/2.10.1/requirements.txt
images/airflow/2.10.3/requirements.txt
images/airflow/2.9.2/requirements.txt
pytest.ini
quality-checks/diff-coverage_test.sh
requirements.txt

*Issue #, if available:* 237
*Description of changes:* 
- Adding coverage tests to the quality-checks workflow that enforces a threshold of 80% coverage on newly added code only.
- The script:
- Fetches the main branch from aws/amazon-mwaa-docker-images (50 commits back) for comparison
- Identifies changes in image directories compared to main
- Runs pytest with coverage in each modified image version's virtual environment
- Uses diff-cover to compare coverage against main branch
- Provides formatted coverage reports showing pass/fail status for each version
- Cleans up temporary files once done
**Note:** This implements an incremental approach to coverage testing, focusing only on new changes.
**Added files:**
- `.coveragerc`: Coverage configuration
- `pytest.ini`: Pytest configuration
- …

Adding diff-based coverage tests to the quality-checks workflow

---

images/airflow/2.10.1/python/mwaa/celery/task_monitor.py
images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/celery/task_monitor.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/celery/task_monitor.py
images/airflow/2.9.2/python/mwaa/entrypoint.py

The current 5 seconds wait time after pausing task consumption is not enough. We have seen some cases where there was still pending SQS.ReceiveMessage requests during the 5 seconds grace period. So this pull request increase the graceful period to 20second, and make it configurable by environment variable.
- `entrypoint.py` reads environment variable `MWAA__CORE__MWAA_WORKER_GRACEFUL_SHUTDOWN_SECONDS`, and make it default to 20 seconds, and pass the value to WorkerTaskMonitor.
- WorkerTaskMonitor will sleep for `MWAA__CORE__MWAA_WORKER_GRACEFUL_SHUTDOWN_SECONDS` seconds after pausing task consumption.

Increase worker graceful shutdown time and make it configurable.

---

images/airflow/2.9.2/python/mwaa/config/setup_environment.py
images/airflow/2.9.2/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/execute_command.py
images/airflow/2.9.2/python/mwaa/logging/config.py
images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py
images/airflow/2.9.2/python/mwaa/utils/user_requirements.py
images/airflow/2.9.2/requirements.txt
quality-checks/unit_tests.sh
requirements.txt
tests/images/airflow/2.9.2/python/mwaa/config/test_setup_environment_2_9_2.py
tests/images/airflow/2.9.2/python/mwaa/test_entrypoint_2_9_2.py
tests/images/airflow/2.9.2/python/mwaa/test_execute_command_2_9_2.py
tests/images/airflow/2.9.2/python/mwaa/utils/test_user_requirements_2_9_2.py

When using airflow versions 2.9.2 and above customer are unable to see error logs when they set their loglevel to `WARNING` or above. The root cause is that in subprocess.py, the line `self.process_logger.info(line.decode("utf-8"))` overrides the log level coming from airflow stream to INFO in [subprocess.py](https://github.com/aws/amazon-mwaa-docker-images/blob/main/images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py#L217).
- Setting process logger level to `DEBUG` to emit all logs and setting root logger to customer's log level to respect customer's log level.
- Refactoring `entrypoint.py` to resolve circular dependency issue and breaking down its logic into different files so all files have single responsibility such as:
- …

Adding fix for incorrect log level bug

---

images/airflow/2.10.1/python/mwaa/config/celery.py
images/airflow/2.10.3/python/mwaa/config/celery.py
images/airflow/2.9.2/python/mwaa/config/celery.py

Added database connection pool configuration settings for Celery to improve reliability and performance:
- Enabled connection health checks with pool_pre_ping
- Set connection recycling to 20 minutes
These settings help prevent stale connections and better manage database connection lifecycle. The lack of this configuration is the root cause behind the notorious `psycopg2.OperationalError: SSL connection has been closed unexpectedly`
To test the new Celery configuration, two MWAA environments were compared, both using RDS proxies with an IdleClientTimeout of 1 minute to accelerate testing. The orange environment, the control, uses the current MWAA default Airflow and Celery configuration, while the blue environment, the subject, uses the updated configuration. Below are the total psycopg2 …

Provide celery with improved db engine pool configuration

---

images/airflow/2.10.1/python/mwaa/config/setup_environment.py
images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.1/python/mwaa/execute_command.py
images/airflow/2.10.1/python/mwaa/logging/config.py
images/airflow/2.10.1/python/mwaa/utils/user_requirements.py
images/airflow/2.10.1/requirements.txt
images/airflow/2.10.3/python/mwaa/config/setup_environment.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/execute_command.py
images/airflow/2.10.3/python/mwaa/logging/config.py
images/airflow/2.10.3/python/mwaa/utils/user_requirements.py
images/airflow/2.10.3/requirements.txt
tests/images/airflow/2.10.1/python/mwaa/config/test_setup_environment_2_10_1.py
tests/images/airflow/2.10.1/python/mwaa/test_entrypoint_2_10_1.py
tests/images/airflow/2.10.1/python/mwaa/test_execute_command_2_10_1.py
tests/images/airflow/2.10.1/python/mwaa/utils/test_user_requirements_2_10_1.py
tests/images/airflow/2.10.3/python/mwaa/config/test_setup_environment_2_10_3.py
tests/images/airflow/2.10.3/python/mwaa/test_entrypoint_2_10_3.py
tests/images/airflow/2.10.3/python/mwaa/test_execute_command_2_10_3.py
tests/images/airflow/2.10.3/python/mwaa/utils/test_user_requirements_2_10_3.py

When using airflow versions 2.9.2 and above customer are unable to see error logs when they set their loglevel to `WARNING` or above. The root cause is that in subprocess.py, the line `self.process_logger.info(line.decode("utf-8"))` overrides the log level coming from airflow stream to INFO in [subprocess.py](https://github.com/aws/amazon-mwaa-docker-images/blob/main/images/airflow/2.9.2/python/mwaa/subprocess/subprocess.py#L217).
- Setting process logger level to `DEBUG` to emit all logs and setting root logger to customer's log level to respect customer's log level.
- Refactoring `entrypoint.py` to resolve circular dependency issue and breaking down its logic into different files so all files have single responsibility such as:
- …

Adding fix for incorrect log level bug for versions 2.10.1 & 2.10.3

---

quality-checks/trufflehog_scan.sh

*Issue* [#236](https://github.com/aws/amazon-mwaa-docker-images/issues/236)
Enable trufflehog scanning for tests folder. 
Removes tests from excluded files to enable scanning.
*Testing*
Trufflescan test and all other quality checks successfully executed

Enable trufflehog scan for tests (#236)

---

images/airflow/2.10.1/healthcheck.py
images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.3/healthcheck.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.9.2/healthcheck.py
images/airflow/2.9.2/python/mwaa/entrypoint.py
tests/images/airflow/2.10.1/python/mwaa/test_entrypoint_2_10_1.py
tests/images/airflow/2.10.1/test_healthcheck.py
tests/images/airflow/2.10.3/python/mwaa/test_entrypoint_2_10_3.py
tests/images/airflow/2.10.3/test_healthcheck.py
tests/images/airflow/2.9.2/python/mwaa/test_entrypoint_2_9_2.py
tests/images/airflow/2.9.2/test_healthcheck.py

- Added `try-catch` in `entrypoint.py` which will handle all the `Exception`s thrown, gracefully and create a `container_unhealthy` marker file (flag)
- Updated `healthcheck.py` to check for the above marker file
- Added UTs for `healthcheck.py`
- Added new test for `entrypoint.py`
- Hardcoded an Exception line in the startup script execution block
- Deployed pinwheel environment : The ECS failed to stabilize which in turn trigger Circuit breaker and that resulted in CFN ROLLBACK
-  CREATE : Iselink for test stack - https://tiny.amazon.com/2l4r798c/IsenLink
- UPDATE : Isenlink for test stack - https://tiny.amazon.com/jq4npiah/IsenLink

Updated entrypoint & healthcheck logic  to handle container exists during grace period

---

images/airflow/2.10.1/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.10.3/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.9.2/python/mwaa/database/migrate_with_downgrade.py

Update the naming for the Airflow database migrate target version to `MWAA__DB__AIRFLOW_TARGET_VERSION`

Rename MWAA__CORE__TARGET_VERSION to MWAA__DB__AIRFLOW_TARGET_VERSION

---

images/airflow/3.0.1/python/mwaa/config/airflow.py

`AIRFLOW__WEBSERVER__CONFIG_FILE ` has been removed from [airflow 3 configuration](https://airflow.apache.org/docs/apache-airflow/3.0.1/configurations-ref.html#web-server)
To specify the web server config path, we should rely on `AIRFLOW__FAB__CONFIG_FILE `. See [Fab Config Reference](https://airflow.apache.org/docs/apache-airflow-providers-fab/2.0.2/configurations-ref.html)

Update essential web server config 3.0.1

---

images/airflow/3.0.2/etc/airflow_constraints.txt

Airflow community updated constraints and rebuilt reference images for Airflow 3.0.2 following release of common-messaging provider 1.0.3 and fab provider 2.2.1.
Updating MWAA constraints file to reflect those changes.
Refer:
- https://github.com/apache/airflow/issues/51854
- https://github.com/apache/airflow/issues/51770
Updated the constraints file.

Updating 3.0.2 constraints based on airflow updates

---

images/airflow/2.10.3/python/mwaa/logging/cloudwatch_handlers.py

*Issue #, if available:* NA
- Refactored the code to use if-elif instead of multiple if statements, since this was causing the task handler to malfunction and not create task log streams in the case where NON_CRITICAL_LOGGING was disabled.
- This was happening since in the case NON_CRITICAL_LOGGING was not enabled, the second if statement would turn out to be false, and hence the else statement was getting executed, which was setting the handler to none again.
*Description of testing:*
- Tested via run.sh and deploying full fledged environments with NON_CRITICAL_LOGGING enabled and disabled, with different formatters for each, running dags for each case ensuring that all loggers work as expected in all cases.
By submitting this pull request, I confirm that you …

Refactoring code to fix TaskHandler errors

---

images/airflow/2.10.1/python/mwaa/config/airflow.py
images/airflow/2.10.3/python/mwaa/config/airflow.py
images/airflow/2.9.2/python/mwaa/config/airflow.py

We set Secure Cookies to true for MWAA environments before 2.9, we should keep this for 2.9 - 2.10.x versions as well. But this config is removed starting from 3.0.0. 

Set Webserver Secure Cookies to True

---

images/airflow/3.0.2/python/mwaa/database/migrate_with_downgrade.py
images/airflow/3.0.2/python/mwaa/entrypoint.py

Porting this change into this 3.0.2 image https://github.com/aws/amazon-mwaa-docker-images/pull/247
The 3.0.2 image was copied off an old version so it does not have the new required migrate-db command
Tested by running the run script with some modifications to go into the migratedb flow

Add migrate-db command for 3.0.2 image

---

images/airflow/2.10.1/python/mwaa/config/setup_environment.py
images/airflow/2.10.3/python/mwaa/config/setup_environment.py
images/airflow/2.11.0/python/mwaa/config/setup_environment.py
images/airflow/2.9.2/python/mwaa/config/setup_environment.py
images/airflow/3.0.3/python/mwaa/config/setup_environment.py

Disable the startup script when running the migrate-db command.
Tested by creating MWAA environments using the updated image.

Skip startup-script when running migrate-db

---

images/airflow/2.10.1/pyrightconfig.json
images/airflow/2.10.1/python/mwaa/celery/task_monitor.py
images/airflow/2.10.1/python/mwaa/webserver/webserver_config.py
quality-checks/lint_python.sh
tests/images/airflow/2.10.1/python/mwaa/celery/test_task_monitor_2_10_1.py

*Issue # (if available):*
N/A
Quality checks currently do not correctly run against files under ./images due to how pyright resolves its configuration from pyrightconfig.json. Specifically, pyright will use the pyrightconfig.json file in your current directory even if you specify a different root path as an argument.
This PR fixes the issue by:
- Extending the linting fixes to Airflow 2.10.1 to ensure consistent code quality across supported versions
- Updated lint_python.sh to include 2.10.1 in the linting process alongside 2.10.3
- Resolved linting issues in task_monitor.py and webserver_config.py for version 2.10.1
- Changed pyrightconfig.json from strict to standard mode for appropriate linting configuration
- Created comprehensive unit tests …

Fix linting quality checks for Airflow 2.10.1

---

images/airflow/3.0.3/python/mwaa/config/airflow.py
images/airflow/3.0.3/python/mwaa/config/setup_environment.py
images/airflow/3.0.3/python/mwaa/webserver/webserver_config.py

- In Airflow 3, for production we set `MWAA__CORE__AUTH_TYPE` to "mwaa-iam" with `FAB` as the Auth Manager , and during local testing via `run.sh`, we set it to "testing", and use the `Simple Auth Manager`, not FAB. The code in `_get_essential_airflow_api_config()` is thus not needed in Airflow 3, and also setting `AUTH_ROLE_PUBLIC` is not useful since that is a FAB config, hence removed them, since they are used to disable auth if we were using FAB.
- Adding `AIRFLOW__API__BASE_URL` and `AIRFLOW__CORE__DATABASE_ACCESS_ISOLATION` to the the protected os environment variable list.
- Refer [link1](https://airflow.apache.org/docs/apache-airflow/2.9.1/configurations-ref.html#auth-backends) and …

Removing FAB auth-disabling irrelevant in AF3 and adding configs to protected env var list

---

images/airflow/2.10.1/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.10.1/python/mwaa/database/reseralize.py
images/airflow/2.10.1/python/mwaa/entrypoint.py
images/airflow/2.10.3/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.10.3/python/mwaa/database/reseralize.py
images/airflow/2.10.3/python/mwaa/entrypoint.py
images/airflow/2.11.0/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.11.0/python/mwaa/database/reseralize.py
images/airflow/2.11.0/python/mwaa/entrypoint.py
images/airflow/2.9.2/python/mwaa/database/migrate_with_downgrade.py
images/airflow/2.9.2/python/mwaa/database/reseralize.py
images/airflow/2.9.2/python/mwaa/entrypoint.py
images/airflow/3.0.3/python/mwaa/database/migrate_with_downgrade.py
images/airflow/3.0.3/python/mwaa/database/reseralize.py
images/airflow/3.0.3/python/mwaa/entrypoint.py

Set reserialize_dags to False on DB upgrades and downgrades as it is loading dags for the upgrades/downgrades. We do not install requirements for this process now so we cannot load their dags.

Set reserialize_dags to False on DB upgrades and downgrades

---

images/airflow/2.10.3/python/mwaa/celery/sqs_broker.py
tests/images/airflow/2.10.3/python/mwaa/celery/test_sqs_broker_2_10_3.py

https://github.com/aws/amazon-mwaa-docker-images/issues/315
Adding a check to make sure `Attributes` field is present and log the response if no to helping debugging the issue

Adding logs to debug unexpected response in celery sqs broker

---

images/airflow/2.10.1/etc/mwaa_essential_constraints.txt
images/airflow/2.10.1/requirements.txt
images/airflow/2.10.3/etc/mwaa_essential_constraints.txt
images/airflow/2.11.0/etc/mwaa_essential_constraints.txt
images/airflow/2.9.2/etc/mwaa_essential_constraints.txt
images/airflow/2.9.2/requirements.txt
images/airflow/3.0.3/etc/mwaa_essential_constraints.txt
images/airflow/3.0.3/requirements.txt

*Issue # (if available):* N/A
Pin fluent-logger version to latest compatible version across all images
- Add fluent-logger==0.11.1 to mwaa_essential_constraints.txt for all versions
- Add fluent-logger to requirements.txt for versions 2.9.2, 2.10.1, and 3.0.3
- Versions 2.10.3 and 2.11.0 already had fluent-logger in requirements.txt
This ensures consistent fluent-logger behavior across all MWAA environments and follows best practices for dependency management by pinning to a specific version (0.11.1) in the constraints files.
*Testing performed:*
- Tested all versions using `./run.sh test-requirements` - all packages installed correctly with fluent-logger==0.11.1
- Ran all versions using `./run.sh` - environments started successfully with the changes
*List any …

Pin fluent-logger version to latest compatible version across all images

---

images/airflow/2.10.1/python/mwaa/celery/sqs_broker.py
images/airflow/2.10.3/python/mwaa/celery/sqs_broker.py
images/airflow/2.11.0/python/mwaa/celery/sqs_broker.py
images/airflow/2.9.2/python/mwaa/celery/sqs_broker.py
images/airflow/3.0.3/python/mwaa/celery/sqs_broker.py
tests/images/airflow/2.10.1/celery/test_sqs_broker_2_10_1.py
tests/images/airflow/2.10.3/python/mwaa/celery/test_sqs_broker_2_10_3.py
tests/images/airflow/2.9.2/python/mwaa/celery/test_sqs_broker_2_9_2.py

Add worker concurrency and consumption metrics to observe worker health better
Add Worker at max concurrency and sqs consumption paused metrics behind feature flag
*Testing*
Deployed on dev aws account and validated that metrics are emitted as expected
Some coverage tests on PR is failing since test setup does not exists for some new versions

Add Worker at max concurrency and sqs consumption paused metrics

---

images/airflow/3.0.3/python/mwaa/config/airflow.py

- Disabling Colored Console logs for AF3, since the move to structlog was causing airflow to send colored logs ( containing ANSI codes for color formatting), which is not useful for MWAA's usecase, since we read the logstream as bytes and forward them to customer, leading to these characters appearing as noise in the worker logs.
- Best solution is disabling colored logs, so airflow doesn't send formatted logs to us in the first place, since for MWAA's logging scheme, they are not useful.
- Here are worker logs after disabling colored logs :
- Below ss shows worker logs with colored logs enabled :

Disabling colored console logs for AF3
